/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2022-12-13 03:19:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class websearchBar_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent {


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);

    try {
      out.write("<h3>Search</h3>\n");
      out.write("<form id=\"searchBar\" method=\"get\" action=\"/customer/list\">\n");
      out.write("          <input class=\"SearchInput\" type=\"text\" id=\"name\" name=\"kw_name\" placeholder=\"Enter customer name to search\"/>\n");
      out.write("          <br />\n");
      out.write("          <select class=\"SearchInput\" name=\"kw_gender\" id=\"gender\">\n");
      out.write("              <option value=\"\">Trong</option>\n");
      out.write("\t\t\t  <option value=\"Nam\">Nam</option>\n");
      out.write("\t\t\t  <option value=\"Nu\">Nu</option>\n");
      out.write("\t\t\t  <option value=\"Khac\">Khac</option>\n");
      out.write("\t\t  </select>\n");
      out.write("          <br />\n");
      out.write("          <input class=\"SearchInput\" type=\"text\" id=\"phone\" name=\"kw_phone\" placeholder=\"Enter customer phone to search\"/>\n");
      out.write("          <br /> \n");
      out.write("          <select class=\"SearchInput\" name=\"kw_membership_level\" id=\"membershipLevel\">\n");
      out.write("              <option value=\"\">Trong</option>\n");
      out.write("              <option value=\"Silver\">Silver</option>\n");
      out.write("              <option value=\"Gold\">Gold</option>\n");
      out.write("              <option value=\"Platinum\">Platinum</option>     \n");
      out.write("          </select>\n");
      out.write("\t\t  <br /> \n");
      out.write("          <input type=\"submit\" value=\"SEARCH CUSTOMER\">\n");
      out.write("   </form>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
